# lidar parameters.
lidar_name: "HDL-32"
reverse_flag: true
h_min_ang: -180
h_max_ang: 180
num_hbeam: 1441

# line extraction parameters.
v_min_line_points: 6
v_seed_line_points: 3
v_least_thresh: 0.055
v_min_line_length: 0.15
v_predict_distance: 0.08
v_pts_missing_tolerance: 1
v_max_pts_gap: 1

h_min_line_points: 6
h_seed_line_points: 3
h_least_thresh: 0.06
h_min_line_length: 0.10
h_predict_distance: 0.08
h_pts_missing_tolerance: 1
h_max_pts_gap: 1

# line clustering parameters.
line_plane_distThreshold: 0.075


